name: Build and Deploy

on:
  push:
    branches: [dev]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy app to VPS
        uses: appleboy/ssh-action@master 
        with: 
            host: ${{ secrets.DEPLOY_HOST }}
            port: ${{ secrets.DEPLOY_PORT }}
            username: ${{ secrets.DEPLOY_USER }}
            password: ${{ secrets.DEPLOY_PASS }} 
            script: |
              cd /var/www/html/leaf-api
              git pull origin dev
              composer install
              php leaf db:migrate -f data
                